INSERT INTO products (name, description, category, price, stock, image_url) VALUES
(
    'SG-03',
    'SHIELD LENS / ACETATE FRAME / FIXED NOSE BRIDGE / UV400 PROTECTION / ONE SIZE',
    'ACCESSORIES',
    140.00,
    60,
    NULL
),
(
    'BP-02',
    'BACKPACK / DOUBLE ZIP CLOSURE / ADJUSTABLE PADDED STRAPS / INNER CONCEALED PADDED LAPTOP SLEEVE / 100% NYLON',
    'ACCESSORIES',
    40.00,
    45,
    NULL
),
(
    'HT-04',
    'OVERSIZED BEANIE / RIBBED KNIT / FOLDED HEM / UNISEX / ONE SIZE / 100% ACRYLIC',
    'ACCESSORIES',
    30.00,
    80,
    NULL
),
(
    'BG-02',
    'DUFFLE BAG / DOUBLE ZIP MAIN COMPARTMENT / REMOVABLE SHOULDER STRAP / 50 X 25 X 25 CM / 100% NYLON',
    'ACCESSORIES',
    120.00,
    20,
    NULL
),
(
    'BT-01',
    'BELT / SINGLE PRONG BUCKLE / FULL GRAIN LEATHER / 35 MM WIDTH / SIZES 30—40',
    'ACCESSORIES',
    60.00,
    35,
    NULL
),
(
    'HT-01',
    'FITTED CAP / STRUCTURED SIX-PANEL / TONAL EMBROIDERED LOGO / LOW PROFILE / 60% COTTON 40% POLYESTER',
    'ACCESSORIES',
    50.00,
    40,
    NULL
);
